blank_issues_enabled: false
contact_links:
  - name: Question / discussion
    url: https://github.com/jejjohnson/pypackage_template/discussions
    about: Ask a question or start a discussion rather than opening an issue.
